name: Build All APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
      - run: chmod +x gradlew
      - name: Build All Debug APK
        run: ./gradlew assembleUniversalDebug assembleArm64Debug assembleArmeabiDebug assembleX86Debug
      - name: Find APK
        run: find . -name "*.apk"
      - uses: actions/upload-artifact@v4
        with:
          name: KR-JBL-PLAYER-ALL-APK
          path: "**/*.apk"
